//* ------------------------------------*\
//    $MISC STRINGS
//* -----------------------------------*/

export const MISC = {
  dash: '-',
  __: '__',
  ALL: 'all',
  BEFOREEND: 'beforeend',
  CHANGE: 'Change ',
  CLEAR_FILTER: 'Clear Filter',
  CLOSE: 'Close',
  CLOSE_FILTERS: 'Close Filters',
  DATA_VISIBLE: 'data-visible',
  EYE_BLINK: 'EyeBlink',
  FALSE: 'false',
  FILTERS: 'Filters',
  fURL1: '//www.facebook.com/sharer.php?u=',
  HEIGHT: 'height',
  IN_VIEWPORT: 'in-viewport',
  LEFT: 'left',
  MENU: 'Menu',
  MQ_HOVER: '(hover: hover)',
  MQ_NO_ANY: '(any-hover: none), (any-pointer: coarse)',
  lURL1: '//www.linkedin.com/shareArticle?mini=true&url=',
  lURL2: '&title=',
  lURL3: '&summary=',
  lURL4: '&source=',
  mURL1: 'mailto:',
  mURL2: '?subject=',
  mURL3: '&body=',
  NAME: 'name',
  NO: 'no',
  NO_RESULTS: 'There are no posts that match that filter combination.',
  LONG: 'long',
  MEDIUM: 'medium',
  POST: 'post',
  POSTS: 'posts',
  PUBLISH: 'publish',
  RIGHT: 'right',
  SQUERY: '&s=',
  SHORT: 'short',
  TABINDEX: 'tabindex',
  TRUE: 'true',
  tHASH: '&hashtags=',
  tURL1: 'https://twitter.com/share?url=',
  tURLText: '&text=',
  tURLVia: '&via=',
  VALUE: 'value',
  WIDTH: 'width',
};
